name: butler

on:
    issue_comment:
        types: [created]

permissions:
    pull-requests: write

jobs:
    chat: # The job name
        runs-on: ubuntu-latest
        steps:
            -   uses: google-github-actions/run-gemini-cli@v0.1.16
                with:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
                    cmd: chat
                    comment_body: ${{ github.event.comment.body }} # This extracts the content of the comment that was made

