name: thanks

on:
    issues:
        types: opened

    workflow_dispatch: # manual trigger

jobs:
    thanks:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            -   uses: actions/github-script@v7
                id: issue_script
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    script: |
                        const issue_number = context.issue.number || 2;
                        console.log(`issue_number: ${issue_number}`);

                        const owner = context.repo.owner;
                        const repo = context.repo.repo;

                        // Lookup issue info
                        const issue = await github.rest.issues.get({
                            repo, owner, issue_number
                        });

                        // Create a comment thanking the contributor
                        const comment = await github.rest.issues.createComment({
                            repo, owner, issue_number,
                            body: `Thank you @${issue.data.user.login} for opening this issue! We appreciate your contribution.`
                        });

                        console.log(`Comment id: ${comment.data.id}`);
                        console.log(`Comment data: ${comment.data}`);

                        // Automatically assign a label to the new issue
                        github.rest.issues.addLabels({
                            repo, owner, issue_number,
                            labels: ['todo-review']
                        });

                        // Return the comment id as output
                        return comment.data.id;

            -   run: echo `comment id=${{ steps.issue_script.outputs.result }}`